In [2]:
import numpy as np
import time
arr_1d=np.array([1,2,3,4,5,67,7])
arr_1d
arr_2d=np.array([[1,2,3,4],[5,67,7,5]])
arr_3=np.array([[1,2,3,4],[5,67,7,5]])

#multiply matrices element wise multiplication
arr_2d*arr_3   

array([[   1,    4,    9,   16],
       [  25, 4489,   49,   25]])

In [3]:
#list
list=[1,2,3,4]
#multiply list
list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
start=time.time()
list=[i*2 for i in range(1000000)]
time.time()-start


0.046547651290893555

In [5]:
start=time.time()
spdi=np.arange(1000000)
time.time()-start

0.0025141239166259766

In [6]:
zeros=np.zeros((2,3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones=np.ones((5,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
#create the matrices of ur reqyuired num
full=np.full((2,4),10)
full

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
random=np.random.random((3,5))
random

array([[0.18798199, 0.8061396 , 0.18314873, 0.29140372, 0.04267477],
       [0.49406203, 0.40802233, 0.03487241, 0.03726077, 0.70556336],
       [0.23377796, 0.79139262, 0.63227236, 0.34654933, 0.83090138]])

In [10]:
#(start,end,gapor differecne)
sequence=np.arange(1,100,4)
sequence

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [11]:
#vector or list are discuss previos
tensor=np.array([[[1,2,3,4,5],[1,2,3,4,5],[55,66,77,88,99]]])
tensor

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [55, 66, 77, 88, 99]]])

Properties of numpy array


In [12]:
tensor=np.array([[[1,2,3,4,5],[1,2,3,4,5],[55,66,77,88,99]]])
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)
tensor.diagonal


(1, 3, 5)
3
int64


<function ndarray.diagonal>

In [13]:
lst = np.arange(1, 21)
c = lst.reshape(5, 4)

print(c)

print(c.transpose())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
