In [2]:
import numpy as np
import time
arr_1d=np.array([1,2,3,4,5,67,7])
arr_1d
arr_2d=np.array([[1,2,3,4],[5,67,7,5]])
arr_3=np.array([[1,2,3,4],[5,67,7,5]])

#multiply matrices element wise multiplication
arr_2d*arr_3   

array([[   1,    4,    9,   16],
       [  25, 4489,   49,   25]])

In [3]:
#list
list=[1,2,3,4]
#multiply list
list*2

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
start=time.time()
list=[i*2 for i in range(1000000)]
time.time()-start


0.062242984771728516

In [5]:
start=time.time()
spdi=np.arange(1000000)
time.time()-start

0.0026879310607910156

In [6]:
zeros=np.zeros((2,3))
zeros


array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
ones=np.ones((5,6))
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [8]:
#create the matrices of ur reqyuired num
full=np.full((2,4),10)
full

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
random=np.random.random((3,5))
random

array([[0.30739162, 0.67109708, 0.49752174, 0.86875973, 0.99207421],
       [0.64002143, 0.2992068 , 0.09419077, 0.19367393, 0.14147043],
       [0.23839448, 0.39646375, 0.43278253, 0.39408091, 0.6607697 ]])

In [10]:
#(start,end,gapor differecne)
sequence=np.arange(1,100,4)
sequence

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [11]:
#vector or list are discuss previos
tensor=np.array([[[1,2,3,4,5],[1,2,3,4,5],[55,66,77,88,99]]])
tensor

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5],
        [55, 66, 77, 88, 99]]])

Properties of numpy array


In [12]:
tensor=np.array([[[1,2,3,4,5],[1,2,3,4,5],[55,66,77,88,99]]])
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)
tensor.diagonal


(1, 3, 5)
3
int64


<function ndarray.diagonal>

In [ ]:
lst = np.arange(1, 21)
c = lst.reshape(5, 4)

print(c)

print(c.transpose())