In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
A=np.array([[56.0,0.0,4.4,68.0],[1.2,104.0,52.0,8.0],[1.8,135.0,99.0,0.9]])
A
cal=A.sum(axis=0)    
cal
percentage=100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

##transpose



In [20]:
b=np.dot(percentage,percentage.T)
b
c=np.random.randn(1,5)
c
d=np.random.randn(5,1)
d

array([[ 0.0581503 ],
       [-0.21449967],
       [-0.43502711],
       [ 0.98737015],
       [ 0.95959691]])