Operations in numpy
 

In [1]:
import numpy as np

In [6]:
arr=np.arange(1,20)

arr
arr[2:20:4]
#negative indexing
arr[-3]

np.int64(17)

In [15]:

array_2d = np.array([[1,2,3,4,5,6,7,8],
                     [1,2,3,4,5,6,7,8]])
print(array_2d[1, 4])
print(array_2d[:])


5
[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [ ]:
#sorting of array
array_2d = np.array([[1,3,5,2,4],[3,2,1,4,2]])
print(np.sort(array_2d,axis=0))
print(np.sort(array_2d,axis=1))


In [20]:
#filter


array_2d = np.array([[1, 3, 5, 2, 4],
                     [3, 2, 1, 4, 2]])

# Filter even numbers
even = array_2d[array_2d % 2 == 0]

print(even)



[2 4 2 4 2]


##use of where


In [32]:
where_result = np.where(array_2d % 2 == 0, array_2d * 5, array_2d)
print(where_result)

[[ 1  3  5 10 20]
 [ 3 10  1 20 10]]


##delete


In [34]:
arr=np.array([1,  3,  5,10, 20])
delete=np.delete(arr,3)
delete

array([ 1,  3,  5, 20])